SIM = icarus
TOPLEVEL_LANG = verilog
VERILOG_SOURCES += \
../verilog/memory_controller.v \
../verilog/memory_decoder.v \
../verilog/bram.v \
../verilog/sram.v \
../verilog/flash.v \
../verilog/peripheral.v \

include $(shell cocotb-config --makefiles)/Makefile.sim