SIM = icarus
TOPLEVEL_LANG = verilog
VERILOG_SOURCES += \
../verilog/cpu.v \
../verilog/alu.v \
../verilog/instruction_decoder.v \
../verilog/barrel_shifter.v

include $(shell cocotb-config --makefiles)/Makefile.sim