SIM = icarus
TOPLEVEL_LANG = verilog
VERILOG_SOURCES += ../verilog/cpu.v ../verilog/bram.v ../verilog/sram.v ../verilog/alu.v ../verilog/barrel_shifter.v

include $(shell cocotb-config --makefiles)/Makefile.sim