SIM = icarus
TOPLEVEL_LANG = verilog
VERILOG_SOURCES += \
cpu/verilog/cpu.v \
cpu/verilog/alu.v \
cpu/verilog/barrel_shifter.v \
memory/bram.v \
memory/sram.v \
memory/flash.v \
uart-controller/verilog/uart.v

include $(shell cocotb-config --makefiles)/Makefile.sim