SIM = icarus
TOPLEVEL_LANG = verilog
VERILOG_SOURCES += cpu/verilog/cpu.v cpu/verilog/bram.v cpu/verilog/alu.v cpu/verilog/barrel_shifter.v uart-controller/verilog/uart.v

include $(shell cocotb-config --makefiles)/Makefile.sim